[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'Townk/vim-autoclose'

# ------------------------------------
# colorscheme tender setting
# ------------------------------------
[[plugins]]
hook_add = '''
    colorscheme tender
    set background=dark
    syntax on
    set t_Co=256
    let $NVIM_TUI_ENABLE_TRUE_COLOR=1
'''
repo = 'jacoborus/tender.vim'
